"""Generated by tools/build_large_icons.py; do not edit by hand."""
import base64
import zlib

DATA = {
    'Liquid Stranger': (60, 28, 'c-rljJ!n%=6vrbqS`{&ciVk*@>LU1oLo23LDHS>ub&_HW;^rcvf{Uv-IXMZgB8o08X)9@r)hbrhMJGZ03TUK=L<OP#PdT?7PVaj;HwpM6eemPmd*6NMo!|XRQmN%@`AVfGhUVwx{eRAjVri1%+UUG=ENkpq$KCo~t$BsSq-*Dww^hf}GVbMHOWUmTC7)A1arxHjN^xE6IA_baldB_izI?7Sw_2QiuDXxU*|Hv_tHU~9QT^n%LY;L?U)(5{xb>jtRU`XF%~zbO%*nFnEaPW!j$02=&Qas)bFL?^xbrdOa<MJzfzYniV$1lo{ysPQ3dzMehrZLy|JRx=f8;w?tsUhNFbf`oXW)3$`|3Seu7D|!2h(6UiN3h^gNGo)^$gdufxfc54%`RF66iY#y4167Fj}iG*Z0u4CD8XHXjRWz!Mi$r)1cHOzH30aPG5@gK7qdDw0_mIeW1wYZ=i+CE5TQzZ;#s(3G+R~=hFspUKPOr*K^=7mj}R@VXoW24Cws_z7_UyT=wL5f`5mefbYy{e%1*Jf=<Kl5q)Q{(JuJ!vm1<qJeU9-U=U0(e?<8xsBpOeo`W6{>m>LMHX+w`nj4gVQf&3jIZ-|Zo`OeU6l@XCD&pJ38P&cd2ZQem_YK^SfSXadd2-zWUWxiWa0QIW{-6kYbqw75z!*q#{XED;ecO_Q!S@r`%H=fJAK<$Jl)1bXOoDCTw(>nlbK&vLfxV)AJ-7>60(=*9F!~OI&)_;Z5Et9?t$uKe%d`j1a(Nc4Qf>toU$lJyt7CGr_%7xU;M_)Q5WEDJs`$FSGfm?PHgo$8-WxMKetpV~_VNSOR&u_yH#zQ`nEl%omxIA`Bj{H3Qo#J40~cuh(RriB{Hmvap4YbXEvogLq4O<peiw2u`nL0$>frizIx7QwcY!+~3$BTF+RLv!{j==oe23I|brJjs^j*lo*Y7VJGHf#'),
}

def sprite_rgba(name):
    width, height, encoded = DATA[name]
    raw = zlib.decompress(base64.b85decode(encoded))
    if len(raw) != width * height * 4:
        raise ValueError("Invalid large icon payload: " + name)
    return tuple(tuple(tuple(raw[(y * width + x) * 4:(y * width + x + 1) * 4])
                       for x in range(width)) for y in range(height))
