#!/usr/bin/env python3
"""Compile assets/icons/large PNGs into a PIL-free CircuitPython icon module."""

import base64
import sys
import zlib
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets" / "icons" / "large"
DESTINATION = ROOT / "large_icon_data.py"


def build():
    entries = []
    names = set()
    for path in sorted(SOURCE.glob("*.png")):
        name = path.stem.replace("_32x32", "").replace("_", " ").strip().title()
        if name in names:
            raise ValueError("Duplicate large icon name: " + name)
        names.add(name)
        with Image.open(path) as image:
            image = image.convert("RGBA")
            width, height = image.size
            if not (1 <= width <= 64 and 1 <= height <= 32):
                raise ValueError("%s must fit within 64x32" % path.name)
            payload = base64.b85encode(zlib.compress(image.tobytes(), 9)).decode("ascii")
        entries.append((name, width, height, payload))

    lines = [
        '"""Generated by tools/build_large_icons.py; do not edit by hand."""',
        "import base64",
        "import zlib",
        "",
        "DATA = {",
    ]
    for name, width, height, payload in entries:
        lines.append("    %r: (%d, %d, %r)," % (name, width, height, payload))
    lines.extend([
        "}",
        "",
        "def sprite_rgba(name):",
        "    width, height, encoded = DATA[name]",
        "    raw = zlib.decompress(base64.b85decode(encoded))",
        "    if len(raw) != width * height * 4:",
        '        raise ValueError("Invalid large icon payload: " + name)',
        "    return tuple(tuple(tuple(raw[(y * width + x) * 4:(y * width + x + 1) * 4])",
        "                       for x in range(width)) for y in range(height))",
        "",
    ])
    DESTINATION.write_text("\n".join(lines), encoding="utf-8")
    return len(entries)


if __name__ == "__main__":
    try:
        print("Compiled %d large icons into %s" % (build(), DESTINATION))
    except ValueError as error:
        sys.exit(str(error))
