"""Bake compressed authoring sprites to raw RGBA for CircuitPython."""

from pathlib import Path

def build(output):
    from large_icon_data import DATA as LARGE_ICONS, sprite_rgba as large_rgba
    from overlay_exact_assets import EXACT_SPRITES, sprite_rgba as exact_rgba
    output = Path(output)
    directory = output / "board_icons"
    directory.mkdir(parents=True, exist_ok=True)
    entries = []
    for name, rows in ([(n, exact_rgba(n)) for n in EXACT_SPRITES]
                       + [(n, large_rgba(n)) for n in LARGE_ICONS]):
        height, width = len(rows), len(rows[0])
        filename = "%02d.rgba" % len(entries)
        (directory / filename).write_bytes(bytes(channel for row in rows
                                                 for pixel in row for channel in pixel))
        entries.append((name, width, height, "/board_icons/" + filename))
    (output / "board_icon_index.py").write_text(
        '"""Generated by tools/build_board_icons.py."""\nICONS = ' + repr(tuple(entries)) + '\n',
        encoding="utf-8",
    )
    return sum(path.stat().st_size for path in directory.iterdir()) + (output / "board_icon_index.py").stat().st_size
